### ISSUE TITLE
Issue using the uploader against a local carto instance

### ISSUE THREAD

**Issue by Kimsing-007** [AppGeo/into-cartodb#13]
I have setup a local CartoDB instance and have managed to get everything running. I am able to import datasets via the front end application.

I am now trying to do bulk uploads (testing with a csv file first) to import data from a .csv file into Carto.

I am receiving a '302 Found' error.

**Comment by calvinmetcalf** [comment]
so this is hardcoded against cartodb (specifically `https://{username}.cartodb.com/api/v2/sql`) so it's probably not uploading to the right place.

Also a 302 isn't an error and should be transparently handled (as a redirect) so that seems strange that this isn't handled

**Comment by knownasilya** [comment]
No longer hard coded.
