### ISSUE TITLE
Cannot create a table with a csv

### ISSUE THREAD

**Issue by GuidoS** [AppGeo/into-cartodb#3]
Using the following command and csv a table was created, but the records were not loaded:
# Command

```
node ./bin.js -c -f ./test.csv -t test3 -u <user> -k <key>
```
# test.csv file contents

```
"abc","def","ghi"
1,2,"a"
3,4,"b"
5,6,"c"
```

Once the table was created I could use the replace mode to push the records in.

**Comment by calvinmetcalf** [comment]
fixed by #7
